[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.17"
pretty_env_logger = "0.4.0"
ron = "0.8.0"
serde = "1.0.160"
tokio = { version = "1.28.0", features = ["full"] }
