[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
ron = "0.8.0"
serde = "1.0.160"
tokio = { version = "1.28.0", features = ["full"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
